database:
  host:     "postgres"
  port:     5432
  user:     "postgres_user"
  password: "postgres_pass"
  name:     "payload"

nats_streaming:
  host:           "nats://nats-streaming"
  port:           4222
  cluster_id:     "NATS"
  client_id:      "subscriber"
  channel_name:   "channel"

http:
  port: 8080


